#!/usr/bin/env python3
"""Builds conf/AdGuardHome.yaml.example for the REPLICA from the server's sanitized example.

The complete set of INTENTIONAL differences between origin and replica is exactly the list in
DIFFERENCES below; everything else is copied unchanged and kept equal by adguard-sync. Run on the
server:  python3 make-pi-example.py
"""
import yaml

SRC = "/srv/compose/adguard/conf/AdGuardHome.yaml.example"
DST = "/srv/compose/pi/adguard/conf/AdGuardHome.yaml.example"

DIFFERENCES = [
    "dns.bind_hosts: 192.168.31.5 (the Pi's LAN address) instead of 192.168.31.2",
    "users: the replica's own admin hash (generated by setup-adguard.sh, never synced)",
    "querylog: memory-only (file_enabled false), 6 h, so the SD card is not written per query",
    "statistics: off (no stats.db writes); query-log and stats settings are NOT synced",
    "http.address stays 127.0.0.1:3000 - same as the origin; reachable only through tailscale serve",
    "not synced: DHCP (off on both), TLS (off on both), web UI theme",
]

d = yaml.safe_load(open(SRC))
d["dns"]["bind_hosts"] = ["192.168.31.5"]
d["querylog"].update({"file_enabled": False, "interval": "6h", "size_memory": 1000, "enabled": True})
d["statistics"].update({"enabled": False})
with open(DST, "w") as f:
    f.write("# Replica config for piserver (Task 21). Generated by make-pi-example.py from the server's\n"
            "# AdGuardHome.yaml.example. Intentional differences from the origin:\n")
    for line in DIFFERENCES:
        f.write("#   - " + line + "\n")
    yaml.dump(d, f, default_flow_style=False, sort_keys=False)
print("wrote", DST)
