# ip  name  [mac]    one child device per line. IPs are static DHCP leases on the router.
192.168.31.60 vlad-motorola-edge-50-fusion 20:36:D0:14:8D:5A
192.168.31.61 vlad-tablet-lenovo 04:34:F6:13:A3:97
192.168.31.30 nastia-tablet-lenovo 04:34:F6:13:A2:99
