[global]
   workgroup = WORKGROUP
   server string = minisserver
   netbios name = MINISSERVER
   security = user
   map to guest = never
   guest ok = no

   server min protocol = SMB3
   client min protocol = SMB3
   server smb encrypt = desired

   interfaces = eno1
   bind interfaces only = yes

   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

[library]
   comment = minisserver ebook/music/video library (read-only)
   path = /srv/library
   browseable = yes
   read only = yes
   guest ok = no
   valid users = smbshare
